title: Tau'ri Docs
description: Documentations for mods and addons from Tau'ri Development
theme: just-the-docs

url: https://docs.justsgmod.eu

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
